language: go

go:
  - 1.15
  - 1.16
  - 1.17

branches:
  only:
    - master
    - /^dev.*$/
    # feat -> dev -> master

services:
  - mysql
  - redis

before_install:
  # mysql
  - mysql -e "CREATE DATABASE db_test;"
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('123') where User='root'; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  # redis
  - redis-cli CONFIG SET requirepass "123"
  # neo4j
  - wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.com stable 3.5' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update && sudo apt-get install neo4j=1:3.5.26
  - sudo service neo4j start
  - sudo neo4j-admin set-initial-password "123"

script:
  - bash ./go.test.sh

after_success:
  - bash < curl -s https://codecov.io/bash
